(ert-deftest elpy-importmagic--add-import-read-args-test ()
  (elpy-testcase ()
    (insert "mysymbol")  ;; the symbol at point
    (when (gethash "importmagic_version" (elpy-config--get-config))
      (mletf* ((called-prompt nil)
               (read-string (prompt initial &optional history def inherit-input-method)
                            initial)
               (completing-read (prompt vals &optional func require-match default history)
                                "import mymodule"))
        (should (equal (elpy-importmagic--add-import-read-args) "import mymodule"))))))
