(ert-deftest elpy-shell-get-or-create-process-should-return-process ()
  (elpy-testcase ()
    (let ((proc (elpy-shell-get-or-create-process)))
      (with-current-buffer (process-buffer proc)
        (should (eq major-mode 'inferior-python-mode))))))
